name: Build Android APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Project
        run: |
          cordova create app com.temp.id TempName
          cp config.xml app/
          cp -r www/* app/www/
          cd app
          
          # Android 12 (Compatível com Google Play)
          cordova platform add android@12.0.0
          
          # --- AQUI ESTÁ A CORREÇÃO ---
          # 1. Instala o Adapter para evitar erro de AndroidX
          cordova plugin add cordova-plugin-androidx-adapter
          
          # 2. Instala o AdMob Novo
          cordova plugin add admob-plus-cordova --save --variable APP_ID_ANDROID="ca-app-pub-3940256099942544~3347511713"
          
          # Aceita licenças
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          
          # Compila gerando APK
          cordova build android --release --packageType=apk --no-telemetry

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: neon-rush-apk
          path: app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
